language: php
php: 7.1
addons:
  hosts:
    - bob.bob.com

before_script:
  - sudo apt-get install nginx
  - composer self-update && composer install
  - sudo cp conf/nginx.conf /etc/nginx/sites-enabled/nginx.conf
  - sudo service nginx restart

after_success:
  - echo WASSUP!!
  - cat /etc/nginx/sites-enabled/default
  - curl http://localhost