language: php
php: 7.1
addons:
  hosts:
    - bob.bob.com

before_script:
  - sudo apt-get install nginx
  - composer self-update && composer install

after_pass:
  - cat /etc/nginx/sites-enabled/default