language: php
php: 7.1
addons:
  hosts:
    - bob.bob.com

before_script:
  - sudo apt-get install nginx
  - composer self-update && composer install
  - sudo cp conf/nginx.conf /etc/nginx/sites-enabled/nginx.conf
  - sudo service nginx restart
  - vendor/bin/codecept build

script: vendor/bin/codecept run

after_success:
  - echo $TRAVIS_COMMIT